name: ssh-sh
description: "Execute shell command via SSH: configure connection and execute commands. 🚀"
author: "Boris Drozdovski"
branding:
  icon: "terminal"
  color: "orange"

inputs:
  HOST:
    description: "Target server hostname or IP address.."
    required: true
  PORT:
    description: "SSH port (default 22)."
    required: false
    default: "22"
  USERNAME:
    description: "SSH username for authentication."
    required: true
  SSH_KEY:
    description: "Private SSH key for secure connection (use secrets)."
    required: true
  RUN_MAIN:
    description: "Bash commands to execute."
    required: false
  RUN_AFTER:
    description: "Optional bash commands to execute."
    required: false

runs:
  using: "composite"
  steps:

    - name: "🔑 Creating ssh key..."
      run: |
        mkdir -p ~/.ssh/
        echo -e "${{ inputs.SSH_KEY }}" > ~/.ssh/target.key
        chmod 600 ~/.ssh/target.key
      shell: bash

    - name: "📄 Setting config for host: ${{ inputs.HOST }}"
      run: |
        cat >>~/.ssh/config <<END
        Host target
          HostName ${{ inputs.HOST }}
          User ${{ inputs.USERNAME }}
          Port 22
          IdentityFile ~/.ssh/target.key
          StrictHostKeyChecking no
        END
      shell: bash

    - name: "🟨 Executing main commands..."
      if: ${{ inputs.RUN_MAIN }}
      run: |
        ssh target "bash -c '${{ inputs.RUN_MAIN }}'"
      shell: bash

    - name: "🟪 Executing additional commands"
      if: ${{ inputs.RUN_AFTER }}
      run: |
        ssh target "bash -c '${{ inputs.RUN_AFTER }}'"
      shell: bash

    - name: "✅ Success"
      run: |
        echo "✅ All tasks completed!"
      shell: bash
